### ISSUE TITLE
Failed to get the number of CUDA devices

### ISSUE THREAD

**Issue by chankeh** [vuptran/cardiac-segmentation#2]
hi,bro,
when i use this code,it occurs problems like this: 
"Failed to get the number of CUDA devices: CUDA driver version is insufficient for CUDA runtime version"

what should i do to solve this matter?
thks!

**Comment by vuptran** [comment]
Do you have a GPU or multiple GPUs in your system?

**Comment by chankeh** [comment]
Only   One   GPU,
Should i  use multiple GPUS ?

**Comment by vuptran** [comment]
You don't need multiple GPUs. If you only have one GPU, then the <gpu_id> argument should be 0. Otherwise, the device ID will not match up. And the model does demand a moderate amount of GPU memory, so your error could be related to your GPU running out of memory.
