### ISSUE TITLE
Run your code on Mac OS X?

### ISSUE THREAD

**Issue by tianqig** [vuptran/cardiac-segmentation#3]
Wonder if it's possible to run your code on Mac OS X? I don't have
an Ubuntu 14.04 installed now.

Or do you see some changes to be done in your code to do so?

Thanks

David

**Comment by boshuru** [comment]
I tested it on my Mac long ago. I think as long as you had installed all required libraries you should be fine.

**Comment by tianqig** [comment]
Thanks for your quick reply, btw, can I just run it on CPU or must on GPU? Thanks

**Comment by boshuru** [comment]
Hi David, I run it on CPU. Just make sure you installed Tensorflow for CPU (pip install tensorflow). Also, I highly recommand using Anaconda to create a virtual Python 2.7 environment. It will prevent possible mess up with your Mac's default Python environment. While installing OpenCV3, you could use a pre-compiled unofficial version from Anaconda distribution.

**Comment by tianqig** [comment]
Hi, Boshuru, great to know the code can be run on CPU. BTW, I have Anaconda on my Mac installed, also Tensorflow, OpenCV, etc. Thanks again for your quick help.
