### ISSUE TITLE
The conversion between pixel and millimeter units

### ISSUE THREAD

**Issue by zq202367** [vuptran/cardiac-segmentation#6]
Hello, I find the SAX_series, but I can't display the corresponding contour coordinates on the DICOM file correctly. 
    From the official document, it shows that each (Xi,Yi) pair representing the coordinates of i pixel in the contour in pixel unites. The conversion factor between pixel and millimeter units can be found by reading the PixelSpacing parameter of a DICOM file.
   I obtain the PixelSpacing which is 1.367188, I don't know how to convert.
   I am looking forward to your reply.

**Comment by vuptran** [comment]
This code does not convert pixel to millimeter units and does not use the PixelSpacing parameter anywhere.
