### ISSUE TITLE
i/o/myo explain

### ISSUE THREAD

**Issue by MarioProjects** [vuptran/cardiac-segmentation#8]
Hello, I would like to take your code as a starting point for LVSC. There is something that is not clear to me and it is the meaning of i/o/ myo and exactly how the works in the submission -> tmp = otmp - itmp.

Why is not myo used? I really do not have much idea... Could not you unify all the segmentations of the same image and learn them all together or?

Thank you

**Comment by vuptran** [comment]
You could certainly segment out only the myocardium part of the image, but I chose to perform two independent segmentations, one for the inner contour and one for the outer contour and subtract the two to get the myocardium. I found that approach to have better accuracy performance.
